language: python
cache: pip
python:
  - "3.6"

before_install:
  - sudo bash llvm-requirements.sh trusty

# command to install dependencies for python using pip
install:
  - pip install -r requirements.txt

# add your test scripts here.
script:
  pytest

# only run tests on these branches
#branches:
#  only:
#    - master
#    - development
