; ModuleID = 'Repositories/OpenChannelSSD-linux/Unfiltered/linux-master_Documentation_scheduler_sched-pelt.c'
source_filename = "Repositories/OpenChannelSSD-linux/Unfiltered/linux-master_Documentation_scheduler_sched-pelt.c"
target datalayout = "e-m:o-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-apple-macosx10.14.0"

@.str = private unnamed_addr constant [43 x i8] c"static const u32 runnable_avg_yN_inv[] = {\00", align 1
@y = common global double 0.000000e+00, align 8
@.str.1 = private unnamed_addr constant [3 x i8] c"\0A\09\00", align 1
@.str.2 = private unnamed_addr constant [8 x i8] c"0x%8x, \00", align 1
@.str.3 = private unnamed_addr constant [6 x i8] c"\0A};\0A\0A\00", align 1
@sum = global i32 1024, align 4
@.str.4 = private unnamed_addr constant [51 x i8] c"static const u32 runnable_avg_yN_sum[] = {\0A\09    0,\00", align 1
@.str.5 = private unnamed_addr constant [5 x i8] c"%5d,\00", align 1
@n = global i32 -1, align 4
@max = global i64 1024, align 8
@.str.6 = private unnamed_addr constant [28 x i8] c"#define LOAD_AVG_PERIOD %d\0A\00", align 1
@.str.7 = private unnamed_addr constant [26 x i8] c"#define LOAD_AVG_MAX %ld\0A\00", align 1
@.str.8 = private unnamed_addr constant [54 x i8] c"static const u32 __accumulated_sum_N32[] = {\0A\09     0,\00", align 1
@.str.9 = private unnamed_addr constant [5 x i8] c"%6d,\00", align 1
@.str.10 = private unnamed_addr constant [72 x i8] c"/* Generated by Documentation/scheduler/sched-pelt; do not modify. */\0A\0A\00", align 1

; Function Attrs: nounwind ssp uwtable
define void @calc_runnable_avg_yN_inv() #0 {
  %1 = alloca i32, align 4
  %2 = alloca i32, align 4
  %3 = bitcast i32* %1 to i8*
  call void @llvm.lifetime.start.p0i8(i64 4, i8* %3) #4
  %4 = bitcast i32* %2 to i8*
  call void @llvm.lifetime.start.p0i8(i64 4, i8* %4) #4
  %5 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([43 x i8], [43 x i8]* @.str, i32 0, i32 0))
  store i32 0, i32* %1, align 4, !tbaa !3
  br label %6

; <label>:6:                                      ; preds = %24, %0
  %7 = load i32, i32* %1, align 4, !tbaa !3
  %8 = icmp slt i32 %7, 32
  br i1 %8, label %9, label %27

; <label>:9:                                      ; preds = %6
  %10 = load double, double* @y, align 8, !tbaa !7
  %11 = load i32, i32* %1, align 4, !tbaa !3
  %12 = sitofp i32 %11 to double
  %13 = call double @llvm.pow.f64(double %10, double %12)
  %14 = fmul double 0x41EFFFFFFFE00000, %13
  %15 = fptoui double %14 to i32
  store i32 %15, i32* %2, align 4, !tbaa !3
  %16 = load i32, i32* %1, align 4, !tbaa !3
  %17 = srem i32 %16, 6
  %18 = icmp eq i32 %17, 0
  br i1 %18, label %19, label %21

; <label>:19:                                     ; preds = %9
  %20 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([3 x i8], [3 x i8]* @.str.1, i32 0, i32 0))
  br label %21

; <label>:21:                                     ; preds = %19, %9
  %22 = load i32, i32* %2, align 4, !tbaa !3
  %23 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([8 x i8], [8 x i8]* @.str.2, i32 0, i32 0), i32 %22)
  br label %24

; <label>:24:                                     ; preds = %21
  %25 = load i32, i32* %1, align 4, !tbaa !3
  %26 = add nsw i32 %25, 1
  store i32 %26, i32* %1, align 4, !tbaa !3
  br label %6

; <label>:27:                                     ; preds = %6
  %28 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([6 x i8], [6 x i8]* @.str.3, i32 0, i32 0))
  %29 = bitcast i32* %2 to i8*
  call void @llvm.lifetime.end.p0i8(i64 4, i8* %29) #4
  %30 = bitcast i32* %1 to i8*
  call void @llvm.lifetime.end.p0i8(i64 4, i8* %30) #4
  ret void
}

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.start.p0i8(i64, i8* nocapture) #1

declare i32 @printf(i8*, ...) #2

; Function Attrs: nounwind readnone speculatable
declare double @llvm.pow.f64(double, double) #3

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.end.p0i8(i64, i8* nocapture) #1

; Function Attrs: nounwind ssp uwtable
define void @calc_runnable_avg_yN_sum() #0 {
  %1 = alloca i32, align 4
  %2 = bitcast i32* %1 to i8*
  call void @llvm.lifetime.start.p0i8(i64 4, i8* %2) #4
  %3 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([51 x i8], [51 x i8]* @.str.4, i32 0, i32 0))
  store i32 1, i32* %1, align 4, !tbaa !3
  br label %4

; <label>:4:                                      ; preds = %34, %0
  %5 = load i32, i32* %1, align 4, !tbaa !3
  %6 = icmp sle i32 %5, 32
  br i1 %6, label %7, label %37

; <label>:7:                                      ; preds = %4
  %8 = load i32, i32* %1, align 4, !tbaa !3
  %9 = icmp eq i32 %8, 1
  br i1 %9, label %10, label %16

; <label>:10:                                     ; preds = %7
  %11 = load double, double* @y, align 8, !tbaa !7
  %12 = load i32, i32* @sum, align 4, !tbaa !3
  %13 = sitofp i32 %12 to double
  %14 = fmul double %13, %11
  %15 = fptosi double %14 to i32
  store i32 %15, i32* @sum, align 4, !tbaa !3
  br label %25

; <label>:16:                                     ; preds = %7
  %17 = load i32, i32* @sum, align 4, !tbaa !3
  %18 = sitofp i32 %17 to double
  %19 = load double, double* @y, align 8, !tbaa !7
  %20 = fmul double %18, %19
  %21 = load double, double* @y, align 8, !tbaa !7
  %22 = fmul double 1.024000e+03, %21
  %23 = fadd double %20, %22
  %24 = fptosi double %23 to i32
  store i32 %24, i32* @sum, align 4, !tbaa !3
  br label %25

; <label>:25:                                     ; preds = %16, %10
  %26 = load i32, i32* %1, align 4, !tbaa !3
  %27 = srem i32 %26, 11
  %28 = icmp eq i32 %27, 0
  br i1 %28, label %29, label %31

; <label>:29:                                     ; preds = %25
  %30 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([3 x i8], [3 x i8]* @.str.1, i32 0, i32 0))
  br label %31

; <label>:31:                                     ; preds = %29, %25
  %32 = load i32, i32* @sum, align 4, !tbaa !3
  %33 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @.str.5, i32 0, i32 0), i32 %32)
  br label %34

; <label>:34:                                     ; preds = %31
  %35 = load i32, i32* %1, align 4, !tbaa !3
  %36 = add nsw i32 %35, 1
  store i32 %36, i32* %1, align 4, !tbaa !3
  br label %4

; <label>:37:                                     ; preds = %4
  %38 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([6 x i8], [6 x i8]* @.str.3, i32 0, i32 0))
  %39 = bitcast i32* %1 to i8*
  call void @llvm.lifetime.end.p0i8(i64 4, i8* %39) #4
  ret void
}

; Function Attrs: nounwind ssp uwtable
define void @calc_converged_max() #0 {
  %1 = alloca i64, align 8
  %2 = alloca i64, align 8
  %3 = bitcast i64* %1 to i8*
  call void @llvm.lifetime.start.p0i8(i64 8, i8* %3) #4
  store i64 0, i64* %1, align 8, !tbaa !9
  %4 = bitcast i64* %2 to i8*
  call void @llvm.lifetime.start.p0i8(i64 8, i8* %4) #4
  %5 = load double, double* @y, align 8, !tbaa !7
  %6 = fmul double 0x41EFFFFFFFE00000, %5
  %7 = fptosi double %6 to i64
  store i64 %7, i64* %2, align 8, !tbaa !9
  br label %8

; <label>:8:                                      ; preds = %24, %0
  %9 = load i32, i32* @n, align 4, !tbaa !3
  %10 = icmp sgt i32 %9, -1
  br i1 %10, label %11, label %17

; <label>:11:                                     ; preds = %8
  %12 = load i64, i64* @max, align 8, !tbaa !9
  %13 = load i64, i64* %2, align 8, !tbaa !9
  %14 = mul nsw i64 %12, %13
  %15 = ashr i64 %14, 32
  %16 = add nsw i64 %15, 1024
  store i64 %16, i64* @max, align 8, !tbaa !9
  br label %17

; <label>:17:                                     ; preds = %11, %8
  %18 = load i64, i64* %1, align 8, !tbaa !9
  %19 = load i64, i64* @max, align 8, !tbaa !9
  %20 = icmp eq i64 %18, %19
  br i1 %20, label %21, label %22

; <label>:21:                                     ; preds = %17
  br label %27

; <label>:22:                                     ; preds = %17
  %23 = load i64, i64* @max, align 8, !tbaa !9
  store i64 %23, i64* %1, align 8, !tbaa !9
  br label %24

; <label>:24:                                     ; preds = %22
  %25 = load i32, i32* @n, align 4, !tbaa !3
  %26 = add nsw i32 %25, 1
  store i32 %26, i32* @n, align 4, !tbaa !3
  br label %8

; <label>:27:                                     ; preds = %21
  %28 = load i32, i32* @n, align 4, !tbaa !3
  %29 = add nsw i32 %28, -1
  store i32 %29, i32* @n, align 4, !tbaa !3
  %30 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([28 x i8], [28 x i8]* @.str.6, i32 0, i32 0), i32 32)
  %31 = load i64, i64* @max, align 8, !tbaa !9
  %32 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([26 x i8], [26 x i8]* @.str.7, i32 0, i32 0), i64 %31)
  %33 = bitcast i64* %2 to i8*
  call void @llvm.lifetime.end.p0i8(i64 8, i8* %33) #4
  %34 = bitcast i64* %1 to i8*
  call void @llvm.lifetime.end.p0i8(i64 8, i8* %34) #4
  ret void
}

; Function Attrs: nounwind ssp uwtable
define void @calc_accumulated_sum_32() #0 {
  %1 = alloca i32, align 4
  %2 = alloca i32, align 4
  %3 = bitcast i32* %1 to i8*
  call void @llvm.lifetime.start.p0i8(i64 4, i8* %3) #4
  %4 = bitcast i32* %2 to i8*
  call void @llvm.lifetime.start.p0i8(i64 4, i8* %4) #4
  %5 = load i32, i32* @sum, align 4, !tbaa !3
  store i32 %5, i32* %2, align 4, !tbaa !3
  %6 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([54 x i8], [54 x i8]* @.str.8, i32 0, i32 0))
  store i32 1, i32* %1, align 4, !tbaa !3
  br label %7

; <label>:7:                                      ; preds = %30, %0
  %8 = load i32, i32* %1, align 4, !tbaa !3
  %9 = load i32, i32* @n, align 4, !tbaa !3
  %10 = sdiv i32 %9, 32
  %11 = add nsw i32 %10, 1
  %12 = icmp sle i32 %8, %11
  br i1 %12, label %13, label %33

; <label>:13:                                     ; preds = %7
  %14 = load i32, i32* %1, align 4, !tbaa !3
  %15 = icmp sgt i32 %14, 1
  br i1 %15, label %16, label %21

; <label>:16:                                     ; preds = %13
  %17 = load i32, i32* %2, align 4, !tbaa !3
  %18 = sdiv i32 %17, 2
  %19 = load i32, i32* @sum, align 4, !tbaa !3
  %20 = add nsw i32 %18, %19
  store i32 %20, i32* %2, align 4, !tbaa !3
  br label %21

; <label>:21:                                     ; preds = %16, %13
  %22 = load i32, i32* %1, align 4, !tbaa !3
  %23 = srem i32 %22, 6
  %24 = icmp eq i32 %23, 0
  br i1 %24, label %25, label %27

; <label>:25:                                     ; preds = %21
  %26 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([3 x i8], [3 x i8]* @.str.1, i32 0, i32 0))
  br label %27

; <label>:27:                                     ; preds = %25, %21
  %28 = load i32, i32* %2, align 4, !tbaa !3
  %29 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @.str.9, i32 0, i32 0), i32 %28)
  br label %30

; <label>:30:                                     ; preds = %27
  %31 = load i32, i32* %1, align 4, !tbaa !3
  %32 = add nsw i32 %31, 1
  store i32 %32, i32* %1, align 4, !tbaa !3
  br label %7

; <label>:33:                                     ; preds = %7
  %34 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([6 x i8], [6 x i8]* @.str.3, i32 0, i32 0))
  %35 = bitcast i32* %2 to i8*
  call void @llvm.lifetime.end.p0i8(i64 4, i8* %35) #4
  %36 = bitcast i32* %1 to i8*
  call void @llvm.lifetime.end.p0i8(i64 4, i8* %36) #4
  ret void
}

; Function Attrs: nounwind ssp uwtable
define void @main() #0 {
  %1 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([72 x i8], [72 x i8]* @.str.10, i32 0, i32 0))
  %2 = call double @llvm.pow.f64(double 5.000000e-01, double 3.125000e-02)
  store double %2, double* @y, align 8, !tbaa !7
  call void @calc_runnable_avg_yN_inv()
  call void @calc_converged_max()
  ret void
}

attributes #0 = { nounwind ssp uwtable "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "less-precise-fpmad"="false" "no-frame-pointer-elim"="true" "no-frame-pointer-elim-non-leaf" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="penryn" "target-features"="+cx16,+fxsr,+mmx,+sahf,+sse,+sse2,+sse3,+sse4.1,+ssse3,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #1 = { argmemonly nounwind }
attributes #2 = { "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "less-precise-fpmad"="false" "no-frame-pointer-elim"="true" "no-frame-pointer-elim-non-leaf" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="penryn" "target-features"="+cx16,+fxsr,+mmx,+sahf,+sse,+sse2,+sse3,+sse4.1,+ssse3,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #3 = { nounwind readnone speculatable }
attributes #4 = { nounwind }

!llvm.module.flags = !{!0, !1}
!llvm.ident = !{!2}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 7, !"PIC Level", i32 2}
!2 = !{!"clang version 7.0.0 (tags/RELEASE_700/final)"}
!3 = !{!4, !4, i64 0}
!4 = !{!"int", !5, i64 0}
!5 = !{!"omnipotent char", !6, i64 0}
!6 = !{!"Simple C/C++ TBAA"}
!7 = !{!8, !8, i64 0}
!8 = !{!"double", !5, i64 0}
!9 = !{!10, !10, i64 0}
!10 = !{!"long", !5, i64 0}
